# Generated by Django 5.1.2 on 2024-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('accno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loanid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ifsccode', models.CharField(max_length=11)),
            ],
        ),
    ]
